[package]
name = "validator-utils"
version = "0.1.0"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.7.3"
gw-types = { git = "https://github.com/jjyr/godwoken.git", branch = "generator-check-contract-script-args", default-features = false }
gw-common = { git = "https://github.com/jjyr/godwoken.git", branch = "generator-check-contract-script-args", default-features = false }
