[package]
name = "validator-utils"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.7.4"
gw-types = { git = "https://github.com/nervosnetwork/godwoken.git", rev = "0adfd15d0f56ca5dfbecd5f4e69f4b3e8e5e7b3e", default-features = false }
gw-common = { git = "https://github.com/nervosnetwork/godwoken.git", rev = "0adfd15d0f56ca5dfbecd5f4e69f4b3e8e5e7b3e", default-features = false }
