[package]
name = "gw-utils"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.9.0"
gw-types = { git = "https://github.com/nervosnetwork/godwoken.git", rev = "1ccd045527b0f2793d4ab1b7b3f575b75531fc5d", default-features = false }
gw-common = { git = "https://github.com/nervosnetwork/godwoken.git", rev = "1ccd045527b0f2793d4ab1b7b3f575b75531fc5d", default-features = false }
